import type { PurchaseCategory } from "./cards"

export interface CategoryOption {
  value: PurchaseCategory
  label: string
  /** Search keywords — include UAE merchants, common typos, and category synonyms. */
  keywords: string[]
  group: "food" | "bills" | "shopping" | "travel"
  /**
   * Plain-English warnings about how banks may classify (MCC code) this category.
   * Shown when a recommended card's reward depends sensitively on the coding.
   */
  mccQuirks?: string[]
}

export const CATEGORY_OPTIONS: CategoryOption[] = [
  // Food & Groceries
  {
    value: "online_food",
    label: "Food delivery – Talabat / Deliveroo / Careem Food",
    keywords: [
      "talabat",
      "careem",
      "careem food",
      "deliveroo",
      "zomato",
      "smiles",
      "food",
      "delivery",
      "takeaway",
      "take away",
      "restaurant delivery",
      "order food",
      "food app",
      "snoonu",
      "noon food",
      "elgrocer",
    ],
    group: "food",
    mccQuirks: [
      "Food-delivery apps usually code as 'restaurants' (dining MCC) — which is what we model.",
      "Pay via Apple/Samsung/Google Pay? Banks like SIB may still treat the transaction as 'online' for the 10% bucket — the wallet path tends to override the merchant MCC.",
    ],
  },
  {
    value: "online_grocery",
    label: "Online groceries – Talabat Mart / Careem / Instashop",
    keywords: [
      "talabat mart",
      "talabat grocery",
      "careem",
      "careem mart",
      "careem market",
      "careem quik",
      "instashop",
      "grocery app",
      "online grocery",
      "noon minutes",
      "noon daily",
      "kibsons",
      "elgrocer",
      "kbsons",
      "1919",
      "barakat",
    ],
    group: "food",
    mccQuirks: [
      "Online grocery sometimes codes as 'supermarket' (good for grocery cards) and sometimes as 'online'/'eCom' (good for wallet cards). Cards like SIB pay 10% on the online MCC but only 0.5% on supermarket — material difference.",
      "Most banks treat 'Carrefour Online' as supermarket MCC. Talabat Mart and Careem Quik are more often 'online'.",
    ],
  },
  {
    value: "grocery",
    label: "Groceries – supermarket / hypermarket (Carrefour, Lulu, etc.)",
    keywords: [
      "carrefour",
      "lulu",
      "supermarket",
      "hypermarket",
      "grocery",
      "groceries",
      "spinneys",
      "waitrose",
      "union coop",
      "co-op",
      "coop",
      "viva",
      "geant",
      "geant easy",
      "west zone",
      "choithrams",
      "milk",
      "vegetables",
      "fruits",
      "bakery",
      "supermart",
      "khairat",
      "almaya",
      "al maya",
      "nesto",
    ],
    group: "food",
    mccQuirks: [
      "Some hypermarket fuel stations (e.g. fuel pumps inside Carrefour/Lulu compounds) code as 'supermarket' — your fuel-card bonus won't apply there.",
      "Hypermarket non-grocery items (electronics, clothes inside Carrefour) typically still code as 'supermarket' on the same swipe.",
    ],
  },
  {
    value: "dining",
    label: "Dining in-store – restaurants / cafes / hotel F&B",
    keywords: [
      "restaurant",
      "cafe",
      "cafés",
      "dine in",
      "dine-in",
      "eat out",
      "coffee",
      "starbucks",
      "costa",
      "tim hortons",
      "brunch",
      "dinner",
      "lunch",
      "bar",
      "bistro",
      "shawarma",
      "pizza",
      "burger",
      "kfc",
      "mcdonald",
      "subway",
      "five guys",
      "shake shack",
      "pf changs",
      "operation falafel",
      "zaatar w zeit",
      "nando",
      "food court",
      "hotel restaurant",
      "afternoon tea",
    ],
    group: "food",
    mccQuirks: [
      "Restaurants inside hotels often code as 'lodging/hotel', not 'dining' — your dining-bonus card may pay the base rate.",
      "Cinema concession stands and theme-park food courts sometimes code as 'entertainment' or 'amusement', not dining.",
      "Food trucks and small stalls may use generic 'retail' MCCs.",
    ],
  },
  {
    value: "fuel",
    label: "Fuel / Petrol station (ADNOC, ENOC, EPPCO, Emarat)",
    keywords: [
      "fuel",
      "petrol",
      "gas station",
      "adnoc",
      "enoc",
      "eppco",
      "epco",
      "emarat",
      "gas",
      "pump",
      "filling station",
      "diesel",
      "shell",
      "exxon",
      "lpg",
      "car wash",
    ],
    group: "bills",
    mccQuirks: [
      "Fuel paid via Apple/Samsung/Google Pay (wallet) may code as 'online/wallet' on some banks — SIB's 10% wallet bonus may or may not trigger. Use the SIB 'fuel-wallet 10%' toggle in settings to choose your assumption.",
      "Petrol-station convenience-store purchases (snacks, car wash) sometimes code as 'supermarket' or 'service station retail', not fuel.",
      "ADNOC food courts and ZOOM stores typically code as supermarket/retail, not fuel.",
    ],
  },
  // Bills
  {
    value: "utilities",
    label: "Utilities / Telecom / Salik / DEWA / Etisalat / Du",
    keywords: [
      "utility",
      "utilities",
      "etisalat",
      "du",
      "salik",
      "bill",
      "bills",
      "dewa",
      "fewa",
      "sewa",
      "addc",
      "adwec",
      "telecom",
      "phone",
      "mobile bill",
      "wifi",
      "internet",
      "electricity",
      "water",
      "tawtheeq",
      "nol top up",
      "darb",
      "yahsat",
    ],
    group: "bills",
    mccQuirks: [
      "Utility/telecom bills paid via the bank's own app/website (e.g. DIB's bill-pay) often earn ZERO rewards on premium points cards.",
      "Salik recharges typically code as 'transportation/government', and most cashback cards give 0.5–3% only.",
      "Nol card top-ups may code as 'transit' or 'utility' depending on channel — different reward outcomes.",
    ],
  },
  {
    value: "government",
    label: "Government / Real estate / Traffic fines / Visa",
    keywords: [
      "rta",
      "tasheel",
      "tamm",
      "government",
      "traffic fine",
      "ejari",
      "visa",
      "visa fee",
      "emirates id",
      "id renewal",
      "amer",
      "typsa",
      "moi",
      "dld",
      "dubai land",
      "real estate fee",
      "court",
      "notary",
      "police fine",
      "fine",
    ],
    group: "bills",
    mccQuirks: [
      "Government services are almost universally a 0–0.5% category — even premium cards strip rewards here.",
      "Pre-paid Salik account top-ups via the bank's app may earn nothing; via the Salik website they sometimes count as 'utility'.",
    ],
  },
  {
    value: "education",
    label: "Education / School / University / Nursery fees",
    keywords: [
      "school",
      "university",
      "tuition",
      "education",
      "college",
      "nursery",
      "kindergarten",
      "kg",
      "fees",
      "term fee",
      "school fee",
      "books",
      "textbook",
      "online course",
      "udemy",
      "coursera",
      "ielts",
      "british council",
    ],
    group: "bills",
    mccQuirks: [
      "Some schools accept payment only via 'TPS' or 'Skiplino' gateways — these may code as 'professional services' rather than 'education'.",
      "Online learning subscriptions (Udemy, Coursera, Skillshare) typically code as 'online' or 'subscriptions', not 'education'.",
    ],
  },
  // Shopping
  {
    value: "online_shopping",
    label: "Online shopping – Amazon / Noon / websites / apps",
    keywords: [
      "amazon",
      "amazon ae",
      "noon",
      "noon.com",
      "online shopping",
      "ecommerce",
      "ebay",
      "namshi",
      "ounass",
      "shein",
      "temu",
      "aliexpress",
      "alibaba",
      "wish",
      "asos",
      "h&m online",
      "zara online",
      "ikea online",
      "apple store",
      "app store",
      "google play",
      "subscription",
      "netflix",
      "spotify",
      "shahid",
      "anghami",
      "icloud",
      "youtube premium",
      "chatgpt",
      "claude",
      "openai",
      "linkedin",
      "domain",
      "hosting",
      "godaddy",
      "namecheap",
      "aws",
      "cloud",
    ],
    group: "shopping",
    mccQuirks: [
      "Card-not-present (online) usually triggers the 'online' MCC, which often gives the best cashback on cards like SIB (10%) and Ajman ULTRACASH (5% if selected).",
      "App-store purchases (Apple/Google) almost always code as 'digital goods' — same online bucket on most cards.",
      "Big marketplaces (Amazon Marketplace, Noon Express) sometimes pass-through the seller's own MCC, which can be 'supermarket' or 'retail' instead of 'online'.",
    ],
  },
  {
    value: "instore_shopping",
    label: "In-store shopping – malls, clothes, electronics, pharmacy, salon",
    keywords: [
      "mall",
      "clothes",
      "electronics",
      "shop",
      "store",
      "dubai mall",
      "mall of emirates",
      "moe",
      "ibn battuta",
      "yas mall",
      "city centre",
      "mirdif",
      "zara",
      "h&m",
      "uniqlo",
      "gap",
      "sharaf dg",
      "jumbo",
      "emax",
      "lulu store",
      "centrepoint",
      "max fashion",
      "splash",
      "homes r us",
      "ikea",
      "pottery barn",
      "west elm",
      "pharmacy",
      "aster",
      "life pharmacy",
      "binsina",
      "bin sina",
      "boots",
      "drugstore",
      "medical store",
      "salon",
      "barber",
      "spa",
      "hair",
      "nails",
      "gym",
      "fitness",
      "fitness first",
      "gold gym",
      "cinema",
      "vox",
      "novo",
      "imax",
      "reel cinemas",
      "amusement",
      "kidzania",
      "img worlds",
      "ferrari world",
      "warner bros",
      "global village",
      "yas waterworld",
      "atlantis",
      "aquaventure",
      "concert",
      "ticket",
      "platinumlist",
      "tickets",
      "taxi",
      "careem ride",
      "uber",
      "rta taxi",
      "metro",
      "nol",
      "parking",
      "rta parking",
      "doctor",
      "clinic",
      "hospital",
      "dental",
      "vet",
      "optician",
      "florist",
      "gift",
      "toys",
      "jewellery",
      "perfume",
      "cosmetics",
      "sephora",
      "watsons",
      "carrefour electronics",
    ],
    group: "shopping",
    mccQuirks: [
      "Pharmacy, salon, gym and cinema all typically code as 'retail' or 'service' — most cards pay only the base 1% here.",
      "Careem / Uber rides (not food) code as 'taxicabs/limousines' — many cashback cards exclude this from accelerated rates.",
      "Cinema ticket boxes vs. concession stand may code differently — the popcorn often counts as dining/F&B, not entertainment.",
    ],
  },
  // Travel
  {
    value: "travel_air",
    label: "Travel – airline tickets",
    keywords: [
      "flight",
      "airline",
      "emirates",
      "etihad",
      "flydubai",
      "fly dubai",
      "air arabia",
      "ticket",
      "airline ticket",
      "booking",
      "skyscanner",
      "wegotravel",
      "wego",
      "kayak",
      "qatar airways",
      "saudia",
      "british airways",
      "lufthansa",
      "turkish airlines",
      "iata",
      "trip ticket",
    ],
    group: "travel",
    mccQuirks: [
      "Airline tickets purchased through OTAs (Booking.com, Wego, Skyscanner) may code as 'travel agency', not 'airline' — some cards only pay the bonus on direct-airline MCCs.",
      "Add-ons like extra baggage or seat selection bought separately on the airline site usually still code as airline.",
    ],
  },
  {
    value: "travel_hotel",
    label: "Travel – hotels / Airbnb / accommodation",
    keywords: [
      "hotel",
      "booking.com",
      "airbnb",
      "stay",
      "agoda",
      "expedia",
      "trivago",
      "resort",
      "accommodation",
      "ihg",
      "marriott",
      "hilton",
      "hyatt",
      "rotana",
      "jumeirah",
      "vacation rental",
      "apartment rental",
      "almosafer",
      "wego stays",
    ],
    group: "travel",
    mccQuirks: [
      "Airbnb codes as 'lodging' on most cards — but some banks have historically classified it as 'professional services'.",
      "Hotel restaurants, spa, room service charged to your hotel folio at checkout will code as 'lodging', not dining/spa.",
      "Local AED hotel stays (staycations) still earn travel rewards on most travel cards since the MCC is lodging — not the location.",
    ],
  },
  {
    value: "other",
    label: "Other / not sure / can't find it",
    keywords: [
      "other",
      "misc",
      "unknown",
      "not sure",
      "dont know",
      "don't know",
      "cant find",
      "can't find",
      "miscellaneous",
    ],
    group: "shopping",
    mccQuirks: [
      "When unsure, banks fall back to the merchant's primary MCC. Most pay-anywhere transactions land in 'retail' or 'professional services' — giving the base 0.5–1% on most cards.",
    ],
  },
]

export const GROUP_LABELS: Record<CategoryOption["group"], string> = {
  food: "Food & Groceries",
  bills: "Bills & Services",
  shopping: "Shopping, Health & Lifestyle",
  travel: "Travel",
}
